name-template: 'v$RESOLVED_VERSION'
tag-template: 'release-$RESOLVED_VERSION'
categories:
  - title: '⚠️ Breaking changes'
    label: 'breaking-change'
  - title: '🚀 Features'
    label: 'enhancement'
  - title: '📘 Documentation'
    label: 'documentation'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '📈 Dependency updates'
    label: 'dependency'
  - title: '🧰 Maintenance'
    label: 'maintenance'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "maintenance"
      - "dependency"
      - "bug"
  default: patch
template: |
  ## What's changed
  $CHANGES
  ## Contributors to this release
  $CONTRIBUTORS
